#!/bin/sh

# upload data containing the metadata is in /dev/stdin
data=$(</dev/stdin)

# json query the metadata field of the upload data
metadata=$(jq -c .Upload.MetaData `$data`)

# run the python standalone binary to evaluate the metadata
./pre-create-bin --metadata "$metadata"

return_code=$?

if [ $return_code -eq 0 ]; then
    echo "SUCCESS $return_code"
else
    cat <<END
    {   
        "RejectUpload": true,
        "HTTPResponse": {
            "StatusCode": 400,
            "Body": "no filename provided"
        }
    }
END
fi

exit 0