version: 1.0

targets:
  edav:
    name: edav
    type: file
    path_template: '{{.Filename}}_{{.UploadId}}'
    path: ./uploads/edav
  ehdi:
    name: ehdi
    type: file
    path_template: '{{.Filename}}_{{.UploadId}}'
    path: ./uploads/ehdi
  eicr:
    name: eicr
    type: file
    path_template: '{{.Filename}}_{{.UploadId}}'
    path: ./uploads/eicr
  ncird:
    name: ncird
    type: file
    path_template: '{{.Filename}}_{{.UploadId}}'
    path: ./uploads/ncird

routing_groups:
  - data_stream_id: pulsenet
    data_stream_route: localsequencefile
    delivery_targets:
      - name: edav
  - data_stream_id: ehdi
    data_stream_route: csv
    delivery_targets:
      - name: ehdi
  - data_stream_id: eicr
    data_stream_route: fhir
    delivery_targets:
      - name: eicr
  - data_stream_id: covid-all-monthly-vaccination
    data_stream_route: csv
    delivery_targets:
      - name: ncird
  - data_stream_id: generic-immunization
    data_stream_route: csv
    delivery_targets:
      - name: ncird
  - data_stream_id: influenza-vaccination
    data_stream_route: csv
    delivery_targets:
      - name: ncird
  - data_stream_id: routine-immunization
    data_stream_route: other
    delivery_targets:
      - name: ncird
  - data_stream_id: rsv-prevention
    data_stream_route: csv
    delivery_targets:
      - name: ncird
  - data_stream_id: dextesting
    data_stream_route: testevent1
    delivery_targets:
      - name: ncird
      - name: eicr
      - name: edav
      - name: ehdi
