global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: upload
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - upload-server:8080
- job_name: "tempo"
  static_configs:
    - targets: ["tempo:3200"]
rule_files:
- "/etc/prometheus/rules.yml"