groups:
  - name: MyRules
    interval: 1m
    rules:
      - record: upload_manifest_count_timestamp_milliseconds
        expr: |
          (
            (timestamp(sum by(data_stream_id, data_stream_route, sender_id) (increase(upload_manifest_count[1m])) > 0)) * 1000
          )
          or
          (
            upload_manifest_count_timestamp_milliseconds offset 1m
          )