version: 1.0

targets:
  edav:
    name: edav
    type: az-blob
    endpoint: 'http://azurite:10000/devstoreaccount1'
    storage_account: 'devstoreaccount1'
    storage_key: $AZURITE_KEY
    container_name: edav

routing_groups:
  - data_stream_id: pulsenet
    data_stream_route: localsequencefile
    delivery_targets:
      - name: edav
        path_template: "{{.DataStreamID}}/{{.DataStreamRoute}}/{{.Filename}}"
  - data_stream_id: dextesting
    data_stream_route: testevent1
    delivery_targets:
      - name: edav
        path_template: "{{.Year}}/{{.Month}}/{{.Day}}/{{.Filename}}_{{.UploadId}}"