version: 1.0

targets:
  edav:
    name: edav
    type: s3
    bucket_name: edav
    access_key_id: minioadmin
    secret_access_key: minioadmin
    endpoint: "http://minio:8000"
    region: us-east-1

routing_groups:
  - data_stream_id: pulsenet
    data_stream_route: localsequencefile
    delivery_targets:
      - name: edav
  - data_stream_id: dextesting
    data_stream_route: testevent1
    delivery_targets:
      - name: edav
