{
 "title": "DEX Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "HTTP Responses",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Active Uploads", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 } },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dex_server_connections_open", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uploads",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(data_stream_id, data_stream_route, sender_id) (increase(upload_manifest_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}