rm -rf uploads/reports
rm -rf uploads/tus-prefix
rm -rf uploads/dex
rm -rf uploads/edav
rm -rf uploads/routing
rm -rf testing/test/reports
rm -rf testing/test/uploads
rm -rf testing/test/dex
rm -rf testing/test/edav
rm -rf testing/test/routing