rm -rf uploads/dex
rm -rf uploads/edav
rm -rf uploads/ehdi
rm -rf uploads/eicr
rm -rf uploads/events
rm -rf uploads/ncird
rm -rf uploads/reports
rm -rf uploads/routing
rm -rf uploads/tus-prefix
rm -rf testing/uploads/dex
rm -rf testing/uploads/edav
rm -rf testing/uploads/ehdi
rm -rf testing/uploads/eicr
rm -rf testing/uploads/events
rm -rf testing/uploads/ncird
rm -rf testing/uploads/reports
rm -rf testing/uploads/routing
rm -rf testing/uploads/tus-prefix
