services:
  cache:
    image: redis:alpine
    restart: always
    command: redis-server
  upload-server:
    image: golang:alpine
    volumes:
      - .:/code
      - ../upload-configs:/upload-configs
    working_dir: /code
    environment:
      - REDIS_CONNECTION_STRING=redis://redispw@cache:6379
    ports:
      - "8080:8080"
      - "8081:8081"
    command: go run ./...
    depends_on:
      - cache
volumes:
  prom_data:
