services:
  cache:
    image: redis:alpine
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    privileged: true
  upload-server:
    image: golang:alpine
    hostname: upload-server
    volumes:
      - .:/code
      - ../upload-configs:/upload-configs
    working_dir: /code
    environment:
      - REDIS_CONNECTION_STRING=redis://redispw@cache:6379
      # Generate a random 32-byte string here https://generate-random.org/encryption-key-generator?count=1&bytes=32&cipher=aes-256-cbc&string=&password=
      - CSRF_TOKEN=${CSRF_TOKEN}
      - DEX_DELIVERY_CONFIG_FILE
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
      - ${UI_PORT:-8081}:${UI_PORT:-8081}
    command: /bin/sh -c "./run-server.sh"
    depends_on:
      - cache
volumes:
  prom_data:
