services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
  upload-server:
    environment:
      - AZURE_STORAGE_ACCOUNT=devstoreaccount1
      # Default test storage key can be found here https://github.com/Azure/Azurite?tab=readme-ov-file#default-storage-account
      - AZURE_STORAGE_KEY=${AZURITE_STORAGE_KEY}
      - AZURE_ENDPOINT=http://azurite:10000/devstoreaccount1
      - TUS_AZURE_CONTAINER_NAME=test
      - DEX_DELIVERY_CONFIG_FILE
    depends_on:
      - azurite
      - cache
