version: "3.9"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  upload-server-integration:
    image: golang:alpine
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - TUS_AZ_STORAGE_NAME=devstoreaccount1
      - TUS_AZ_STORAGE_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - TUS_AZ_CONTAINER_NAME=test
      - TUS_AZ_CONTAINER_ENDPOINT=http://azurite:10000/devstoreaccount1
      - TUS_AZ_CONTAINER_ACCESS_TYPE=container
      - DEX_AZ_STORAGE_NAME=devstoreaccount1
      - DEX_AZ_STORAGE_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - DEX_AZ_CONTAINER_NAME=config
      - DEX_AZ_CONTAINER_ENDPOINT=http://azurite:10000/devstoreaccount1
      - PODMAN_CI_TESTS=true
    command: go test --tags=integration -v -coverprofile=c.out -coverpkg=./... ./cmd
    depends_on:
      - azurite