version: "3.8"

services:
  localstack:4.0.3:
    image: localstack/localstack
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=sns,sqs,s3
    volumes:
      - ./configs/local/localstack:/etc/localstack/init/ready.d
  upload-server:
    environment:
      - SQS_SUBSCRIBER_EVENT_ARN=arn:aws:sqs:us-east-1:000000000042:test-topic
      - SQS_SUBSCRIBER_TOPIC_ARN=arn:aws:sns:us-east-1:000000000042:test-topic
      - SNS_PUBLISHER_EVENT_ARN=arn:aws:sns:us-east-1:000000000042:test-topic
      - SNS_REPORTER_EVENT_ARN=arn:aws:sns:us-east-1:000000000000:report-topic
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=LSIAQAAAAAAVNCBMPNSG
      - AWS_SECRET_ACCESS_KEY=bogus
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
