services:
  cache:
    extends:
      file: docker-compose.yml
      service: cache
    ports:
      - 6380
    command: redis-server --port 6380
  upload-server:
    extends:
      file: docker-compose.yml
      service: upload-server
    environment:
      - REDIS_CONNECTION_STRING=redis://redispw@cache:6380
      - SERVER_HOSTNAME=upload-server
      - SERVER_PORT=8082
      - UI_PORT=8083
    ports:
      - 8082
      - 8083
  playwright:
    image: mcr.microsoft.com/playwright:v1.48.0-focal
    build: .
    volumes:
      - ../tests/smoke/playwright:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c 'sleep 60; npm install; npm test --workers=1'
    environment:
      - CI=${CI}
      - SERVER_URL=http://upload-server:8082
      - UI_URL=http://upload-server:8083
    depends_on:
      - upload-server
