services:
  upload-server:
    command: go test -coverprofile=c.out -coverpkg=./... ./... -tags=integration
    environment:
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
    depends_on:
      - minio
      - azurite
      - cache
