services:
  cache:
    image: redis:alpine
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    command: redis-server
  upload-server:
    image: golang:alpine
    container_name: upload-server
    volumes:
      - .:/code
      - ../upload-configs:/upload-configs
    working_dir: /code
    environment:
      - REDIS_CONNECTION_STRING=redis://redispw@cache:6379
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
      - ${UI_PORT:-8081}:${UI_PORT:-8081}
    command: /bin/sh -c "go build -o phdou ./cmd && ./phdou"
    depends_on:
      - cache
volumes:
  prom_data:
