services:
  upload-server:
    image: golang:alpine
    container_name: upload-server
    volumes:
      - .:/code
      - ../upload-configs:/upload-configs
    working_dir: /code
    ports:
      - 8082:8082
      - 8083:8083
    command: /bin/sh -c "./run-server.sh"
    environment:
      - SERVER_HOSTNAME=upload-server
      - SERVER_PORT=8082
      - UI_PORT=8083
  playwright:
    image: mcr.microsoft.com/playwright:v1.48.0-focal
    container_name: playwright
    volumes:
      - ../tests/smoke/playwright:/app
      - /app/node_modules
    working_dir: /app
    command: /bin/sh -c "npm install; ./wait-for-it.sh http://upload-server:8083; npm test --workers=1"
    environment:
      - CI=${CI}
      - SERVER_URL=http://upload-server:8082
      - UI_URL=http://upload-server:8083
      - TEST_REPORT_JSON=fs-test-report.json
      - TEST_RESULTS_DIR=./test-results/fs-results
    depends_on:
      - upload-server
