services:
  upload-server:
    image: golang:alpine
    container_name: upload-server
    volumes:
      - .:/code
      - ../upload-configs:/upload-configs
    working_dir: /code
    environment:
      # Generate a random 32-byte string here https://generate-random.org/encryption-key-generator?count=1&bytes=32&cipher=aes-256-cbc&string=&password=
      - CSRF_TOKEN=p67SW3MKNtR7QvxCrrc/QCjX6JFet9/Hsd1+5ZEfpBe5rrSraZftryOQMz5zcYsy
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
      - ${UI_PORT:-8081}:${UI_PORT:-8081}
    command: /bin/sh -c "./run-server.sh"
volumes:
  prom_data:
