networks:
  e2e-fs-network:

services:
  upload-server:
    image: golang:alpine
    container_name: upload-server-fs
    volumes:
      - .:/code
      - ../upload-configs:/upload-configs
    working_dir: /code
    environment:
      - SERVER_HOSTNAME=upload-server-fs
    command: /bin/sh -c "./run-server.sh"
    networks:
      - e2e-fs-network
  playwright:
    image: mcr.microsoft.com/playwright:v1.48.0-focal
    container_name: playwright-fs
    volumes:
      - ../tests/smoke/playwright:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CI=${CI}
      - SERVER_URL=http://upload-server-fs:8080
      - UI_URL=http://upload-server-fs:8081
      - TEST_REPORTS_DIR=${TEST_REPORTS_DIR:-./test-reports}
      - TEST_REPORT_JSON=fs-test-report.json
      - TEST_RESULTS_DIR=${TEST_RESULTS_DIR:-./test-results}
    command: /bin/sh -c "npm install; ./wait-for-it.sh $$UI_URL; npm test --workers=1"
    networks:
      - e2e-fs-network
