apiVersion: 1

datasources:
- name: Prometheus
  uid: prometheus-datasource
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: true
- name: Loki
  type: loki
  url: http://loki:3100