name: Upload Reports Custom

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - tst
          - stg
          - prod
      datastreams:
        description: "Data Stream(s) (celr_csv,celr_hl7v2)"
        required: true
        default: ""
      start_date:
        description: "Start Date (YYYY-MM-DDTHH:MM:SSZ)"
        required: true
        default: ""
      end_date:
        description: "End Date (YYYY-MM-DDTHH:MM:SSZ)"
        required: true
        default: ""

jobs:
  run-action:
    runs-on: [self-hosted, linux]
    environment: ${{ inputs.env }}

    steps:
      - name: Checkout Go application repository
        uses: actions/checkout@v4
        with:
          repository: CDCgov/data-exchange-upload/upload-reports
          path: upload-reports

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20" # Adjust to your Go version

      - name: Build Go application
        run: go build -o app
        working-directory: ./upload-reports

      - name: Run Go application with secrets and inputs
        run: ./app
        working-directory: ./upload-reports
        env:
          DATASTREAMS: "${{ inputs.datastreams }}"
          START_DATE: "${{ inputs.start_date }}"
          END_DATE: "${{ inputs.end_date }}"
          TARGET_ENV: "${{ inputs.env }}"
          PS_API_ENDPOINT: "${{ secrets.PS_API_ENDPOINT }}"

      - name: Upload output CSV as GitHub Actions artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: upload-reports-csv
          path: ./upload-reports/upload-report.csv
