name: Upload Reports Daily

on:
  schedule:
    - cron: "0 14 * * *" # 10 AM EST = 14:00 UTC (Adjust for daylight savings if necessary)

jobs:
  run-action:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Go application repository
        uses: actions/checkout@v4
        with:
          repository: CDCgov/data-exchange-upload/upload-reports
          path: upload-reports

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20" # Adjust to your Go version

      # Calculate the start date and end date for the last 24 hours (10 AM Eastern)
      - name: Set default date values (start_date and end_date)
        id: set_dates
        run: |
          current_time=$(TZ="America/New_York" date '+%Y/%m/%d 10:00:00')
          start_time=$(TZ="America/New_York" date --date="yesterday 10:00:00" '+%Y/%m/%d 10:00:00')

          echo "start_date=${start_time}" >> $GITHUB_ENV
          echo "end_date=${current_time}" >> $GITHUB_ENV

      - name: Build Go application
        run: go build -o app
        working-directory: ./upload-reports

      - name: Run Go application with defaults
        run: ./app
        working-directory: ./upload-reports
        env:
          DATASTREAMS: "test_csv,test_pdf" # Default value for datastreams
          START_DATE: "${{ env.start_date }}"
          END_DATE: "${{ env.end_date }}"
          TARGET_ENV: "dev"
          PS_API_ENDPOINT: "${{ secrets.PS_API_ENDPOINT }}"
          S3_BUCKET_NAME: "${{ secrets.S3_BUCKET_NAME }}"
          S3_ENDPOINT: "${{ secrets.S3_ENDPOINT }}"

      - name: Upload output CSV as GitHub Actions artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: upload-reports-csv
          path: ./upload-reports/upload-report.csv # Make sure this matches the path to the saved CSV
