version: 1.0

targets:
  edav:
    name: edav
    type: az-blob
    endpoint: $EDAV_ENDPOINT
    container_name: $EDAV_CHECKPOINT_CONTAINER_NAME
    tenant_id: $EDAV_TENANT_ID
    client_id: $EDAV_CLIENT_ID
    client_secret: $EDAV_CLIENT_SECRET

routing_groups:
  - data_stream_id: pulsenet
    data_stream_route: localsequencefile
    delivery_targets:
      - name: edav
        path_template: "{{.DataStreamID}}-{{.DataStreamRoute}}/{{.Filename}}"
  - data_stream_id: dextesting
    data_stream_route: testevent1
    delivery_targets:
      - name: edav
        path_template: "phdo-testing/{{.Year}}/{{.Month}}/{{.Day}}/{{.Filename}}_{{.UploadId}}"
