version: 1.0

targets:
  edav:
    name: edav
    type: az-blob
    endpoint: $EDAV_ENDPOINT
    container_name: $EDAV_CHECKPOINT_CONTAINER_NAME
    tenant_id: $EDAV_TENANT_ID
    client_id: $EDAV_CLIENT_ID
    client_secret: $EDAV_CLIENT_SECRET
  ncird:
    name: ncird
    type: az-blob
    endpoint: $NCIRD_ENDPOINT
    container_name: $NCIRD_CHECKPOINT_CONTAINER_NAME
    tenant_id: $NCIRD_TENANT_ID
    client_id: $NCIRD_CLIENT_ID
    client_secret: $NCIRD_CLIENT_SECRET

routing_groups:
  - data_stream_id: pulsenet
    data_stream_route: localsequencefile
    delivery_targets:
      - name: edav
        path_template: "{{.DataStreamID}}-{{.DataStreamRoute}}/{{.Filename}}"
  - data_stream_id: covid-all-monthly-vaccination
    data_stream_route: csv
    delivery_targets:
      - name: ncird
        path_template: covid-all-monthly-vaccination-csv/{{.Year}}/{{.Month}}/{{.Day}}/{{.Filename}}
  - data_stream_id: generic-immunization
    data_stream_route: csv
    delivery_targets:
      - name: ncird
        path_template: generic-immunization-other/{{.Year}}/{{.Month}}/{{.Day}}/{{.Filename}}
  - data_stream_id: influenza-vaccination
    data_stream_route: csv
    delivery_targets:
      - name: ncird
        path_template: influenza-vaccination-csv/{{.Year}}/{{.Month}}/{{.Day}}/{{.Filename}}
  - data_stream_id: routine-immunization
    data_stream_route: other
    delivery_targets:
      - name: ncird
        path_template: routine-immunization-zip/{{.Year}}/{{.Month}}/{{.Day}}/{{.Filename}}
  - data_stream_id: rsv-prevention
    data_stream_route: csv
    delivery_targets:
      - name: ncird
        path_template: rsv-prevention-csv/{{.Year}}/{{.Month}}/{{.Day}}/{{.Filename}}
  - data_stream_id: dextesting
    data_stream_route: testevent1
    delivery_targets:
      - name: edav
        path_template: "phdo-testing/{{.Year}}/{{.Month}}/{{.Day}}/{{.Filename}}_{{.UploadId}}"
