{
 "title": "PHDO Snapshot",
 "description": "Visualization of various metrics sourced by PHDO microservices to give an idea of overall health and performance of the system.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Uploads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (dex_server_active_uploads{job=\"upload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Deliveries",
   "type": "gauge",
   "description": "Gauge to show the number of files currently being processed for delivery",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(target) (dex_server_active_deliveries{job=\"upload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Goroutines",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (go_goroutines{job=\"upload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivery Failures",
   "type": "stat",
   "description": "Shows total delivery failures for each target",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(target) (dex_server_deliveries_total{job=\"upload\", result=\"failure\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "gauge",
   "description": "Gauge of messages ready to be handled from the queues that the upload server is subscribed to.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(queue) (dex_server_queue_messages{job=\"upload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Since Last Successful Upload",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "upload_manifest_count_timestamp_milliseconds{job=\"upload\"}",
     "legendFormat": "{{data_stream_id}}/{{data_stream_route}}/{{sender_id}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Median Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(dex_server_upload_speed_bytes_per_second_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Average Upload Throughput",
   "type": "timeseries",
   "description": "Shows a snapshot of upload usage and its effect on the system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(tusd_bytes_received[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Uploads Finished",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(tusd_uploads_finished{job=\"upload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uploads Delivered",
   "type": "timeseries",
   "description": "Total number of files that have been successfully delivered to their target destinations.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "sum(dex_server_deliveries_total{job=\"upload\", result=\"completed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(tusd_bytes_received{job=\"upload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uploads By Datastream/Route",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(data_stream_id, data_stream_route) (increase(upload_manifest_count{job=\"upload\"}[$timeRange]))",
     "legendFormat": "{{data_stream_id}}/{{data_stream_route}}"
    }
   ]
  },
  {
   "title": "Upload Event Totals",
   "type": "timeseries",
   "description": "Total number of events that have been published or subscribed by the upload server",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by(type, op) (dex_server_events_total{job=\"upload\", type!=\"upload-status\"})",
     "legendFormat": "{{op}}/{{type}}"
    }
   ]
  }
 ]
}