#!/bin/sh

# upload data containing the metadata is in /dev/stdin
data="$(cat /dev/stdin)"

id=$(jq '.Upload.ID' `$data`)

# json query the metadata field of the upload data
metadata=$(jq '.Upload.MetaData' `$data`)

# run the python standalone binary to evaluate the metadata
./post-create-bin --id "$id" --metadata "$metadata"
