openapi: 3.0.1

info:
  title: ocio-dmz-dev-upload-destination
  description: ''
  version: '1.0'

servers:
  - url: https://apidev.cdc.gov/destination
  
paths:
  "/":
    get:
      summary: UploadDestinations
      description: Returns all allowed destinations
      operationId: get-uploaddestinations
      responses:
        '200':
          description: Success

components:
  securitySchemes:
    sams:
      type: oauth2
      description: This API uses OAuth-2 with the password grant flow. 
      flows:
        password:
          tokenUrl: https://apidev.cdc.gov/oauth
          scopes:
            dex:status: dex status
            
security:
   - sams: []