name: TST - Build and Deploy Branch

on:
  workflow_dispatch:

jobs:
  remote-trigger:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: build-and-deploy-branch-tst.yml
      REF: "${{ github.ref_name }}" # Resolves to the branch being tested
    secrets: inherit
