name: TST - Build and Deploy Branch

on:
  workflow_dispatch:
    inputs:
      REF:
        description: Branch from CDCgov/data-exchange-upload that you want to deploy to the tst environment.
        default: main
        required: true
        type: string

jobs:
  remote-trigger:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: build-and-deploy-branch-tst.yml
      REF: ${{ inputs.REF }}
    secrets: inherit
