# Copied from https://dev.to/ysfaran/how-to-use-playwright-with-github-actions-and-github-pages-4gdl
name: Delete Playwright Report for Branch

on:
  delete:
  workflow_dispatch:
    inputs:
      REF:
        description:
          Branch from CDCgov/data-exchange-upload that you want to deploy to the tst environment.
        default: main
        required: true
        type: string

# ensures that currently running Playwright workflow of deleted branch gets cancelled
concurrency:
  group: ${{ inputs.REF }} # TODO - change back to github.event.ref
  cancel-in-progress: true

jobs:
  delete_reports:
    name: Delete Playwright Reports
    runs-on: ubuntu-latest
    env:
      # Contains all reports for deleted branch
      BRANCH_NAME: ${{ inputs.REF }} # TODO - change back to github.event.ref
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Set Git User
        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Delete Reports for Branch
        if: ${{ github.event.ref_type == 'branch' }}
        timeout-minutes: 3
        working-directory: playwright-reports
        run: |
          path=(${BRANCH_NAME//\// })
          base_dir=${path[0]}

          if [ -z "$(ls -A $base_dir)" ]; then
            rm -rf $base_dir
            git add .

            git commit -m "workflow: remove all reports for branch $BRANCH_NAME"
            git pull origin gh-pages --rebase -s recursive -X ours
          fi
