# Copied from https://dev.to/ysfaran/how-to-use-playwright-with-github-actions-and-github-pages-4gdl
name: Delete Playwright Report for Branch

on:
  # delete:
  pull_request:

jobs:
  delete_reports:
    name: Delete Playwright Reports
    runs-on: ubuntu-latest
    env:
      # Contains all reports for deleted branch
      BRANCH_NAME: UPLOAD-1825/playwright-ghpages # TODO - change back to github.event.ref
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Set Git User
        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Delete Reports for Branch
        # if: ${{ github.event.ref_type == 'branch' }}
        timeout-minutes: 3
        working-directory: playwright-reports/
        run: |
          # Normalize the branch name to convert '/' to '_' so it doesn't create extra subdirectories
          branch=${{ env.BRANCH_NAME }}
          norm_branch=(${branch//\//_})

          if [[ -d "$norm_branch" ]]; then
          rm -rf $norm_branch
          git add .
          git commit -m "workflow: remove all reports for branch $BRANCH_NAME"
          git pull origin gh-pages --rebase -s recursive -X ours
          git push
            echo "Deleted Playwright Reports for $branch from GitHub Pages" >> "$GITHUB_STEP_SUMMARY"
          else 
            echo "Could not find Playwright Reports for $branch to delete" >> "$GITHUB_STEP_SUMMARY"
          fi
