name: "Deploy Function App Release Candidate - Staging"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  staging:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: function-app-rc-matrix.yml
      REF: ${{ github.ref }}
    secrets: inherit
