name: "TST - Deploy Release Candidate"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  staging:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: deploy-rc-tst.yml
      REF: '${{ github.ref_name }}'  # Resolves to the tag that is pushed
    secrets: inherit
