name: "Deploy Release Candidate - Staging"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  staging:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: function-app-rc.yml
      REF: ${{ github.ref_name }}  # Resolves to the tag that is pushed
    secrets: inherit
