name: 'Playwright Tests'

on:
  workflow_call:

defaults:
  run:
    working-directory: upload-server/

jobs:
  run-tests:
    strategy:
      max-parallel: 3
      matrix:
        include:
          - title: "E2E FS Tests"
            name: "fs-to-fs"
            compose: "./docker-compose.e2e.yml"
          - title: "E2E Azure Tests"
            name: "azure-to-azure"
            compose: "./docker-compose.e2e.azurite.yml"
          - title: "E2E AWS Tests"
            name: "aws-to-aws"
            compose: "./docker-compose.e2e.minio.yml"
          - title: "E2E FS -> Azure & AWS Tests"
            name: "fs-to-azure-and-aws"
            compose: "./docker-compose.e2e.all.yml"
          - title: "E2E AWS -> Azure Tests"
            name: "aws-to-azure"
            compose: "./docker-compose.e2e.minio-azurite.yml"
    name: ${{ matrix.title }}
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CI: true
      AZURITE_STORAGE_KEY: ${{ secrets.AZURITE_STORAGE_KEY }}
      # The compose file sends this variable into the Playwright configs
      TEST_REPORTS_DIR: /playwright/test-reports/${{ matrix.name }}/
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compose
        run: pip3 install podman-compose
      - name: Run E2E Tests
        id: test
        run:
          podman-compose -f ${{ matrix.compose }} up --build --exit-code-from playwright --abort-on-container-exit
      - name: Test Report
        # Piping the logs through perl so that we can append the test title to make where they are coming from clearer
        # The only annotation types produced by the `github` report are 'debug', 'notice', 'warning', and 'error' so this should cover them all
        run:
          podman-compose -f ${{ matrix.compose }} logs -f playwright | perl -pe 's/::(debug|notice|warning|error) title=/$&\[${{ matrix.title }}\] /g'
      - name: Upload Playwright Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.name }}
          path: tests/smoke/playwright/test-reports/${{ matrix.name }}
          retention-days: 10
      - name: Tear Down Containers
        run: podman-compose -f ${{ matrix.compose }} down
    outputs:
      actualResult: ${{ steps.test.conclusion }}
  merge-reports:
    name: Merge Report Artifacts
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: playwright-report
          pattern: playwright-report-*
          separate-directories: true
          delete-merged: true
  publish:
    needs: [merge-reports]
    uses: ./.github/workflows/push-to-gh-pages.yml
    with:
      ARTIFACT_ID: playwright-report
      DEPLOY_TO: playwright-reports/${{ github.ref_name }}/${{ github.run_id }}/
      COMMIT_MSG: "add HTML report for run-id ${{ github.run_id }}"
