name: 'Playwright Tests'

on:
  workflow_call:
    inputs:
      BRANCH_NAME:
        type: string
        required: true
      RUN_ID:
        type: string
        required: true
      EVENT_TYPE:
        type: string
        required: true

defaults:
  run:
    working-directory: upload-server/

jobs:
  e2e-tests:
    strategy:
      matrix:
        include:
          - title: 'E2E FS Tests'
            name: 'fs-to-fs'
            compose: './docker-compose.e2e.yml'
          - title: 'E2E Azure Tests'
            name: 'azure-to-azure'
            compose: './docker-compose.e2e.azurite.yml'
          - title: 'E2E AWS Tests'
            name: 'aws-to-aws'
            compose: './docker-compose.e2e.minio.yml'
          - title: 'E2E FS -> Azure & AWS Tests'
            name: 'fs-to-azure-and-aws'
            compose: './docker-compose.e2e.all.yml'
          - title: 'E2E AWS -> Azure Tests'
            name: 'aws-to-azure'
            compose: './docker-compose.e2e.minio-azurite.yml'
    name: ${{ matrix.title }}
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CI: true
      AZURITE_STORAGE_KEY: ${{ secrets.AZURITE_STORAGE_KEY }}
      # The compose file sends this variable into the Playwright configs
      HTML_REPORT_DIR: ${{ matrix.name }}-html-report
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compose
        run: pip3 install podman-compose
      - name: Run E2E Tests
        id: test
        run:
          podman-compose -f ${{ matrix.compose }} up --build --exit-code-from playwright
          --abort-on-container-exit
      - name: Print Test Report
        # Piping the logs through perl so that we can append the test title to make where they are coming from clearer
        # The only annotation types produced by the `github` report are 'debug', 'notice', 'warning', and 'error' so this should cover them all
        run:
          podman-compose -f ${{ matrix.compose }} logs -f playwright | perl -pe
          's/::(debug|notice|warning|error) title=/$&\[${{ matrix.title }}\] /g'
      - name: Upload Playwright Reports
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.name }}
          path: tests/smoke/playwright/test-reports
          retention-days: 1
      - name: Tear Down Containers
        run: podman-compose -f ${{ matrix.compose }} down
    outputs:
      actualResult: ${{ steps.test.conclusion }}

  generate-report:
    name: Generate HTML Report from Blob Reports
    needs: [e2e-tests]
    runs-on: ubuntu-latest
    env:
      ARTIFACT_ID: playwright-reports
    outputs:
      deploy_to: ${{ steps.variables.outputs.deploy_to }}
      commit_msg: ${{ steps.variables.outputs.commit_msg }}
      artifact_id: ${{ env.ARTIFACT_ID }}
    steps:
      - name: Checkout Playwright Files
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download Blob Reports
        uses: actions/download-artifact@v4
        with:
          pattern: playwright-report-*
          path: tests/smoke/playwright/test-reports
          merge-multiple: true
      - name: Merge Multiple Reports into Single Report
        working-directory: tests/smoke/playwright
        run: npm ci && npm run merge-reports ./test-reports
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_ID }}
          path: tests/smoke/playwright/test-reports
          retention-days: 1
      - name: Set Report Path and Message
        id: variables
        run: |
          if [[ ${{ inputs.EVENT_TYPE }} == 'push' ]]; then
            echo "deploy_to=${{ env.ARTIFACT_ID }}/main/" >> "$GITHUB_OUTPUT"
            echo "commit_msg='update Playwright report for main'" >> "$GITHUB_OUTPUT"
          else
            echo "deploy_to=${{ env.ARTIFACT_ID }}/${{ inputs.BRANCH_NAME }}/${{ inputs.RUN_ID }}/" >> "$GITHUB_OUTPUT"
            echo "commit_msg='add Playwright report for branch ${{ inputs.BRANCH_NAME }}, run-id ${{ inputs.RUN_ID }}'" >> "$GITHUB_OUTPUT"
          fi

  publish:
    needs: [generate-report]
    uses: ./.github/workflows/push-to-gh-pages.yml
    with:
      ARTIFACT_ID: ${{ needs.generate-report.outputs.artifact_id }}
      DEPLOY_TO: ${{ needs.generate-report.outputs.deploy_to }}
      COMMIT_MSG: ${{ needs.generate-report.outputs.commit_msg }}
