name: Template - Run E2E Tests Using Docker-Compose File

on:
  workflow_call:
    inputs:
      COMPOSE_FILENAME:
        type: string
        required: true
      STORAGE_TYPE:
        type: string
        required: true

defaults:
  run:
    working-directory: upload-server/

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      CI: true
      AZURITE_STORAGE_KEY: ${{ (inputs.STORAGE_TYPE == 'azure') && secrets.AZURITE_STORAGE_KEY }}
      TEST_REPORT_GITHUB: ${{ inputs.STORAGE_TYPE}}-github-report.md
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compose
        run: pip3 install podman-compose
      - name: Run E2E Tests
        id: test
        run: podman-compose -f ${{ inputs.COMPOSE_FILENAME }} up --build --exit-code-from playwright --abort-on-container-exit
      - name: Tear Down Containers
        run: podman-compose -f ${{ inputs.COMPOSE_FILENAME }} down
      - name: Test Report
        id: summary
        run: cat ${{ github.workspace }}/tests/smoke/playwright/test-reports/${{ env.TEST_REPORT_GITHUB }} >> "$GITHUB_STEP_SUMMARY"
    outputs:
      actualResult: ${{ steps.test.conclusion }}
