name: Template - Run E2E Tests Using Docker-Compose File

on:
  workflow_call:
    inputs:
      TEST_TITLE:
        type: string
        required: true
      COMPOSE_FILENAME:
        type: string
        required: true
      STORAGE_TYPE:
        type: string
        required: true

defaults:
  run:
    working-directory: upload-server/

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CI: true
      AZURITE_STORAGE_KEY:
        ${{ (inputs.STORAGE_TYPE == 'azure' || inputs.STORAGE_TYPE == 'all') &&
        secrets.AZURITE_STORAGE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compose
        run: pip3 install podman-compose
      - name: Run E2E Tests
        id: test
        run:
          podman-compose -f ${{ inputs.COMPOSE_FILENAME }} up --build --exit-code-from playwright
          --abort-on-container-exit
      - name: Test Report
        # Piping the logs through perl so that we can append the TEST_TITLE to make where they are coming from clearer
        # The only annotation types produced by the `github` report are 'debug', 'notice', 'warning', and 'error' so this should cover them all
        run:
          podman-compose -f ${{ inputs.COMPOSE_FILENAME }} logs -f playwright | perl -pe
          's/::(debug|notice|warning|error) title=/$&\[${{ inputs.TEST_TITLE }}\] /g'
      - name: Tear Down Containers
        run: podman-compose -f ${{ inputs.COMPOSE_FILENAME }} down
    outputs:
      actualResult: ${{ steps.test.conclusion }}
