name: "Gradle Function App CI Template"

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        description: "Subdirectory where the function app project files are located."
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '8'
      - name: Build
        run: CI=true ./gradlew build
