name: "Mirror To CDC Gov"

on: [workflow_dispatch, push]

jobs:
  get-install-token:
    name: "Get Install Token"
    runs-on: ubuntu-latest
    outputs:
      installToken: ${{ steps.get-token.outputs.token }}
    defaults:
      run:
        working-directory: .github/workflows/scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Dependencies
        run: |
          pip install pyjwt
          pip install cryptography
          pip install requests
      - name: Get Install Token
        id: get-token
        env:
          PRIVATE_KEY: ${{ secrets.CDCENT_CDCGOV_SYNC_PRIVATE_KEY }}
        run: python get-install-token.py --app-id ${{ secrets.CDCENT_CDCGOV_SYNC_APP_ID }} --installation-id ${{ secrets.CDCENT_CDCGOV_SYNC_INSTALLATION_ID }} >> $GITHUB_OUTPUT
  mirror:
    name: "Mirror Commits To CDC Gov"
    runs-on: ubuntu-latest
    needs: get-install-token
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone to CDCGov
        env:
          GITHUB_TOKEN: ${{ needs.get-install-token.outputs.installToken }}
        run: git push --mirror git@github.com:CDCgov/data-exchange-upload.git
