name: Mirror Repository
on:
  repository_dispatch:
    types: [mirror]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/main'
          repository: 'cdcent/data-exchange-upload'
          fetch-depth: 0
      - name: Mirror repository
        run: |
          git remote add target git@github.com:cdcent/data-exchange-upload.git
          git push --mirror target
