name: "Mirror To CDC Gov"

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  sync-mirror:
    name: "sync-mirror"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Push to CDCGov
        uses: cdcent/cdcent-cdcgov-sync-action@v1.0
        with:
          destination-repo: data-exchange-upload
          app-id: ${{ secrets.CDCENT_CDCGOV_SYNC_APPID }}
          installation-id: ${{ secrets.CDCENT_CDCGOV_SYNC_INSTALLATION_ID }}
          private-key: ${{ secrets.CDCENT_CDCGOV_SYNC_PRIVATE_KEY }}
