name: "Mirror To CDC Gov"

on: push

jobs:
  mirror:
    name: "Mirror Commits To CDC Gov"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone to CDCGov
        run: git push --mirror git@github.com:CDCgov/data-exchange-upload.git
