name: Publish Swagger UI to Github Pages

on:
  pull_request:
    paths:
      - 'swagger/**'
  push:
    branches:
      - main
    paths:
      - 'swagger/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1.1.6
        with:
          spec-file: ./swagger/openapi.yml
          output: ./swagger/swagger-docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger/swagger-docs
          publish_branch: gh-pages
