name: RELEASE CANDIDATE - Build and push release candidate to ImageHub

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  remote-trigger:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: release-candidate.yml
      REF: ${{ github.ref_name }} # Resolves to the tag that is pushed
    secrets: inherit
