name: "Supplemental API Function App Remote CD Dev"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - supplemental-api-function-app/**

jobs:
  dev:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: supplemental-api-function-app-cd-dev.yml
    secrets: inherit
