name: "Supplemental API Function App Remote CD Staging"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    paths:
      - supplemental-api-function-app/**

jobs:
  staging:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: supplemental-api-function-app-cd-staging.yml
      REF: ${{ github.ref }}
    secrets: inherit
