name: "CI - Upload Server"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - upload-server/**

defaults:
  run:
    working-directory: upload-server/

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - name: Vet
        run: go vet ./...
      - name: Run Tests
        run: go test -coverprofile=c.out -coverpkg=./... ./...
      - name: Show coverage
        run: go tool cover -func=c.out
      - name: Build Check
        run: go build -o upload-server ./cmd/main.go
  simulation-test:
    name: Simulation Test
    runs-on: ubuntu-latest
    env:
      AZURITE_STORAGE_KEY: ${{ secrets.AZURITE_STORAGE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compose
        run: pip3 install podman-compose
      - name: Run Tests
        run: podman-compose -f docker-compose.yml -f docker-compose.azurite.yml -f docker-compose.minio.yml -f docker-compose.testing.yml up --exit-code-from upload-server
      - name: Show coverage
        run: go tool cover -func=c.out
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    env:
      CI: true
      TEST_REPORTS_DIR: ./playwright-report
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compse
        run: pip3 install podman-compose
      - name: Pull Images
        run: podman-compose -f docker-compose.e2e.yml pull
      - name: Run Tests - File System
        run: PLAYWRIGHT_JSON_OUTPUT_NAME=file-system-report.json podman-compose -f docker-compose.e2e.yml up --no-recreate --exit-code-from playwright
  #     - name: Run Tests - Azure
  #       run: ZURITE_STORAGE_KEY=${{ secrets.AZURITE_STORAGE_KEY }} PLAYWRIGHT_JSON_OUTPUT_NAME=azure-report.json podman-compose -f docker-compose.yml -f docker-compose.azurite.yml -f docker-compose.e2e.yml up --exit-code-from playwright
  #     - name: Run Tests - AWS
  #       run: PLAYWRIGHT_JSON_OUTPUT_NAME=aws-report.json podman-compose -f docker-compose.yml -f docker-compose.minio.yml -f docker-compose.e2e.yml up --exit-code-from playwright
  #     - uses: actions/upload-artifact@v4
  #       if: ${{ !cancelled() }}
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30
  run-fortify-scan:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: fortify.yml
      REF: ${{ github.head_ref }}
    secrets: inherit
