name: "DEV - Tus Post-Receive Hook"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - tus/file-hooks/upload-status/**

jobs:
  dev:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: tus-post-receive-hook-cd-dev.yml
    secrets: inherit
