name: "Tus Pre-Create Hook Build and Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - tus/file-hooks/metadata-verify/**

jobs:
  dev:
    uses: ./.github/workflows/tus-hooks-build-and-deploy-template.yml
    with:
      HOOK_NAME: pre-create
      WORKING_DIRECTORY: tus/file-hooks/metadata-vericy
      BUILD_SCRIPT: build-pre-create-bin.sh
