name: "CI - Upload Server"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - upload-server/**

defaults:
  run:
    working-directory: upload-server/

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - name: Vet
        run: go vet ./...
      - name: Run Tests
        run: go test -coverprofile=c.out -coverpkg=./... ./...
      - name: Show coverage
        run: go tool cover -func=c.out
      - name: Build Check
        run: go build -o upload-server ./cmd/main.go
  simulation-test:
    name: Simulation Test
    runs-on: ubuntu-latest
    env:
      AZURITE_STORAGE_KEY: ${{ secrets.AZURITE_STORAGE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compose
        run: pip3 install podman-compose
      - name: Run Tests
        run: podman-compose -f docker-compose.yml -f docker-compose.azurite.yml -f docker-compose.minio.yml -f docker-compose.testing.yml up --exit-code-from upload-server
      - name: Show coverage
        run: go tool cover -func=c.out
  e2e-tests-fs:
    name: E2E Tests - File System Storage
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CI: true
      REPORT_DIRECTORY: ${{ github.workspace }}/tests/smoke/playwright/test-reports
      TEST_REPORT_GITHUB: fs-github-report.txt
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compose
        run: pip3 install podman-compose
      - name: Run E2E Tests
        id: test
        run: podman-compose -f docker-compose.e2e.yml up --build --exit-code-from playwright --abort-on-container-exit
      - name: Test Report
        run: cat ${{ env.REPORT_DIRECTORY }}/${{ env.TEST_REPORT_GITHUB }}
      - name: Tear Down Containers
        run: podman-compose -f docker-compose.e2e.yml down
    outputs:
      actualResult: ${{ steps.test.conclusion }}
  e2e-tests-azure:
    name: E2E Tests - Azure Blob Storage
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CI: true
      REPORT_DIRECTORY: ${{ github.workspace }}/tests/smoke/playwright/test-reports
      TEST_REPORT_GITHUB: azure-github-report.txt
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compose
        run: pip3 install podman-compose
      - name: Run E2E Tests
        id: test
        env:
          AZURITE_STORAGE_KEY: ${{ secrets.AZURITE_STORAGE_KEY }}
        run: podman-compose -f docker-compose.e2e.azure.yml up --build --exit-code-from playwright --abort-on-container-exit
      - name: Test Report
        run: cat ${{ env.REPORT_DIRECTORY }}/${{ env.TEST_REPORT_GITHUB }}
      - name: Tear Down Containers
        run: podman-compose -f docker-compose.e2e.azure.yml down
    outputs:
      actualResult: ${{ steps.test.conclusion }}
  e2e-tests-aws:
    name: E2E Tests - AWS S3 Storage
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CI: true
      REPORT_DIRECTORY: ${{ github.workspace }}/tests/smoke/playwright/test-reports
      TEST_REPORT_GITHUB: aws-github-report.txt
    steps:
      - uses: actions/checkout@v4
      - name: Install podman compose
        run: pip3 install podman-compose
      - name: Run E2E Tests
        id: test
        run: podman-compose -f docker-compose.e2e.aws.yml up --build --exit-code-from playwright --abort-on-container-exit
      - name: Test Report
        run: cat ${{ env.REPORT_DIRECTORY }}/${{ env.TEST_REPORT_GITHUB }}
      - name: Tear Down Containers
        run: podman-compose -f docker-compose.e2e.aws.yml down
    outputs:
      actualResult: ${{ steps.test.conclusion }}
  run-fortify-scan:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: fortify.yml
      REF: ${{ github.head_ref }}
    secrets: inherit
