name: "CI - Upload Server"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - upload-server/**

defaults:
  run:
    working-directory: upload-server/

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - name: Vet
        run: go vet ./...
      - name: Run Tests
        run: go test -coverprofile=c.out -coverpkg=./... ./testing
      - name: Show coverage
        run: go tool cover -func=c.out
      - name: Build Check
        run: go build -o upload-server ./cmd/main.go