name: "Tus Pre-Create Hook CI"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - tus/file-hooks/metadata-verify/**

defaults:
  run:
    working-directory: tus/file-hooks/metadata-verify

jobs:
  run-tests:
    uses: ./.github/workflows/tus-hooks-ci-template.yml
    with:
      WORKING_DIRECTORY: tus/file-hooks/metadata-verify
