name: "Tus Pre-Create Hook CI"

on:
  pull_request:
    paths:
      - tus/file-hooks/metadata-verify/**

defaults:
  run:
    working-directory: tus/file-hooks/metadata-verify

jobs:
  dev:
    uses: ./.github/workflows/tus-hooks-ci-template.yml
    with:
      HOOK_NAME: pre-create
      WORKING_DIRECTORY: tus/file-hooks/metadata-verify
      BUILD_SCRIPT: podman-build-pre-create-bin.sh  
