name: "CI - Tus Server V2"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - spikes/tusd-go-server-v2/**

defaults:
  run:
    working-directory: spikes/tusd-go-server-v2/

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      # You can test your matrix by printing the current Go version
      - name: Run Tests
        run: go test ./...