name: Tus Post-Receive Hook Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - tus/file-hooks/upload-status/**

jobs:
  dev:
    uses: ./.github/workflows/tus-hooks-build-and-deploy-template.yml
    with:
      HOOK_NAME: post-receive
      WORKING_DIRECTORY: tus/file-hooks/upload-status
      BUILD_SCRIPT: build-post-receive-bin.sh
