name: "DEV - Upload Processor"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - upload-processor/**

jobs:
  dev:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: bulk-file-upload-function-app-cd-dev.yml
    secrets: inherit
