name: "Upload Function App Build and Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - BulkFileUploadFunctionApp/**

jobs:
  build-and-deploy:
    name: "build-and-deploy"
    runs-on: [self-hosted, azure-function]
    defaults:
      run:
        working-directory: BulkFileUploadFunctionApp
    steps:
     - name: Log in with Azure
       uses: azure/login@v1
       with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
     - name: Checkout
       uses: actions/checkout@v3
     - name: Build and Deploy
       run: ./deploy.sh dev
