name: "Upload Configs CD Dev"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - upload-configs/**

jobs:
    dev:
        uses: ./.github/workflows/remote-cd-trigger-template.yml
        with:
            WORKFLOW: upload-configs-cd-dev.yml
        secrets: inherit
