name: DEV - Upload Server

on:
  workflow_dispatch:
  push:
    branches:
        - main
    paths:
        - upload-server/**

jobs:
  remote-trigger:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: upload-server.yml
    secrets: inherit

